services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: kingsleys-admin
    restart: unless-stopped
    networks:
      - traefik

    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.rule=Host(`dwh.projectkingsleys.com`)
      - traefik.http.routers.frontend.entrypoints=websecure
      - traefik.http.routers.frontend.tls=true
      - traefik.http.services.frontend.loadbalancer.server.port=80

networks:
  traefik:
    external: true